# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 06:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.NullBooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=32, unique=True)),
                ('has_changed_slug', models.BooleanField(default=False, editable=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y-%m-%d/', verbose_name='Avatar picture')),
                ('bio', models.TextField(default='', verbose_name='Short Bio')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email verified')),
                ('skills', models.ManyToManyField(blank=True, related_name='skills', to='profiles.Skill')),
            ],
        ),
        migrations.AddField(
            model_name='userapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userapplication',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Position'),
        ),
        migrations.AddField(
            model_name='userapplication',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
