# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 09:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=32, unique=True)),
                ('has_changed_slug', models.BooleanField(default=False, editable=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y-%m-%d/', verbose_name='Avatar picture')),
                ('bio', models.TextField(default='', verbose_name='Short Bio')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email verified')),
                ('skills', models.ManyToManyField(related_name='skills', to='projects.Skill')),
            ],
        ),
    ]
