# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapplication',
            name='is_accepted',
            field=models.NullBooleanField(default=None),
        ),
    ]
